//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAspNetApp.ServiceReference1xxx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientOrganizationModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ClientOrganizationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Organization_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Request_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Txt_SearchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Type_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Organization_Id {
            get {
                return this.Organization_IdField;
            }
            set {
                if ((this.Organization_IdField.Equals(value) != true)) {
                    this.Organization_IdField = value;
                    this.RaisePropertyChanged("Organization_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request_status {
            get {
                return this.Request_statusField;
            }
            set {
                if ((object.ReferenceEquals(this.Request_statusField, value) != true)) {
                    this.Request_statusField = value;
                    this.RaisePropertyChanged("Request_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemRole {
            get {
                return this.SystemRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemRoleField, value) != true)) {
                    this.SystemRoleField = value;
                    this.RaisePropertyChanged("SystemRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Txt_Search {
            get {
                return this.Txt_SearchField;
            }
            set {
                if ((object.ReferenceEquals(this.Txt_SearchField, value) != true)) {
                    this.Txt_SearchField = value;
                    this.RaisePropertyChanged("Txt_Search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Type_id {
            get {
                return this.Type_idField;
            }
            set {
                if ((this.Type_idField.Equals(value) != true)) {
                    this.Type_idField = value;
                    this.RaisePropertyChanged("Type_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1xxx.IClientOrganization")]
    public interface IClientOrganization {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/DoWork", ReplyAction="http://tempuri.org/IClientOrganization/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/GetClientOrganization", ReplyAction="http://tempuri.org/IClientOrganization/GetClientOrganizationResponse")]
        System.Data.DataSet GetClientOrganization(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/GetunassignedOrganizations", ReplyAction="http://tempuri.org/IClientOrganization/GetunassignedOrganizationsResponse")]
        System.Data.DataSet GetunassignedOrganizations(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/GetPrimaryContactInformationForEmail", ReplyAction="http://tempuri.org/IClientOrganization/GetPrimaryContactInformationForEmailRespon" +
            "se")]
        System.Data.DataSet GetPrimaryContactInformationForEmail(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/GetRequestLetterForEmail", ReplyAction="http://tempuri.org/IClientOrganization/GetRequestLetterForEmailResponse")]
        System.Data.DataSet GetRequestLetterForEmail(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/DeleteOrganizationClientSide", ReplyAction="http://tempuri.org/IClientOrganization/DeleteOrganizationClientSideResponse")]
        void DeleteOrganizationClientSide(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/InsertintoClientOrganizationLinkup", ReplyAction="http://tempuri.org/IClientOrganization/InsertintoClientOrganizationLinkupResponse" +
            "")]
        void InsertintoClientOrganizationLinkup(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/UpdateintoClientOrganizationLinkup", ReplyAction="http://tempuri.org/IClientOrganization/UpdateintoClientOrganizationLinkupResponse" +
            "")]
        void UpdateintoClientOrganizationLinkup(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/UpdateintoClientOrganizationLinkupDeny", ReplyAction="http://tempuri.org/IClientOrganization/UpdateintoClientOrganizationLinkupDenyResp" +
            "onse")]
        void UpdateintoClientOrganizationLinkupDeny(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOrganization/SwitchClient", ReplyAction="http://tempuri.org/IClientOrganization/SwitchClientResponse")]
        string SwitchClient(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientOrganizationChannel : TestAspNetApp.ServiceReference1xxx.IClientOrganization, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientOrganizationClient : System.ServiceModel.ClientBase<TestAspNetApp.ServiceReference1xxx.IClientOrganization>, TestAspNetApp.ServiceReference1xxx.IClientOrganization {
        
        public ClientOrganizationClient() {
        }
        
        public ClientOrganizationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientOrganizationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientOrganizationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientOrganizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Data.DataSet GetClientOrganization(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            return base.Channel.GetClientOrganization(mdl, str_conn);
        }
        
        public System.Data.DataSet GetunassignedOrganizations(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string con) {
            return base.Channel.GetunassignedOrganizations(mdl, con);
        }
        
        public System.Data.DataSet GetPrimaryContactInformationForEmail(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            return base.Channel.GetPrimaryContactInformationForEmail(mdl, str_conn);
        }
        
        public System.Data.DataSet GetRequestLetterForEmail(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            return base.Channel.GetRequestLetterForEmail(mdl, str_conn);
        }
        
        public void DeleteOrganizationClientSide(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            base.Channel.DeleteOrganizationClientSide(mdl, str_conn);
        }
        
        public void InsertintoClientOrganizationLinkup(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            base.Channel.InsertintoClientOrganizationLinkup(mdl, str_conn);
        }
        
        public void UpdateintoClientOrganizationLinkup(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            base.Channel.UpdateintoClientOrganizationLinkup(mdl, str_conn);
        }
        
        public void UpdateintoClientOrganizationLinkupDeny(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            base.Channel.UpdateintoClientOrganizationLinkupDeny(mdl, str_conn);
        }
        
        public string SwitchClient(TestAspNetApp.ServiceReference1xxx.ClientOrganizationModel mdl, string str_conn) {
            return base.Channel.SwitchClient(mdl, str_conn);
        }
    }
}
